insert into satellites(name, life_exists, first_spacecraft_landing_date, planet_id) values ('Moon', 'OPEN_QUESTION', '1959-09-13', 3);
insert into satellites(name, life_exists, planet_id) values ('Phobos', 'NO_DATA', 4);
insert into satellites(name, life_exists, planet_id) values ('Deimos', 'NO_DATA', 4);
insert into satellites(name, life_exists, planet_id) values ('Io', 'NO_DATA', 5);
insert into satellites(name, life_exists, planet_id) values ('Europa', 'NO_DATA', 5);
insert into satellites(name, life_exists, planet_id) values ('Ganymede', 'NO_DATA', 5);
insert into satellites(name, life_exists, planet_id) values ('Callisto', 'NO_DATA', 5);
insert into satellites(name, life_exists, planet_id) values ('Titan', 'NO_DATA', 6);
insert into satellites(name, life_exists, planet_id) values ('Ariel', 'NO_DATA', 7);
insert into satellites(name, life_exists, planet_id) values ('Umbriel', 'NO_DATA', 7);
insert into satellites(name, life_exists, planet_id) values ('Titania', 'NO_DATA', 7);
insert into satellites(name, life_exists, planet_id) values ('Oberon', 'NO_DATA', 7);
insert into satellites(name, life_exists, planet_id) values ('Miranda', 'NO_DATA', 7);
insert into satellites(name, life_exists, planet_id) values ('Triton', 'NO_DATA', 8);
